# Generated by Django 3.2 on 2023-05-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
